In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/drive/MyDrive/myfirstproject/notebook/Bengaluru_House_Data.csv')

In [3]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
df['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [5]:
df['bhk']= df['size'].apply(lambda x: int(str(x).split(' ')[0]) if pd.notnull(x) else None)

In [6]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2.0

In [7]:
df['area_type'].unique()

array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area'], dtype=object)

In [8]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
bhk               16
dtype: int64

In [9]:
df.dropna(subset=['bhk'], inplace=True)

In [10]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2.0

In [11]:
df.describe()

               bath       balcony         price           bhk
count  13247.000000  12711.000000  13304.000000  13304.000000
mean       2.692610      1.584376    112.582035      2.803743
std        1.341458      0.817263    148.988398      1.294974
min        1.000000      0.000000      8.000000      1.000000
25%        2.000000      1.000000     50.000000      2.000000
50%        2.000000      2.000000     72.000000      3.000000
75%        3.000000      2.000000    120.000000      3.000000
max       40.000000      3.000000   3600.000000     43.000000

In [12]:
def convert_sqft_to_num(x):
  tokens = str(x).split('-')
  if len(tokens) == 2:
    return (float(tokens[0])+float(tokens[1]))/2
  try:
    return float(x)
  except:
    return None
df['total_sqft'] = df['total_sqft'].apply(convert_sqft_to_num)

In [13]:
df['sqrft/bhk'] = df['total_sqft']/df['bhk']

In [14]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk,sqrft/bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2.0,528.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4.0,650.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00,3.0,480.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3.0,507.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00,2.0,600.0

In [15]:
df.isnull().sum()

area_type          0
availability       0
location           1
size               0
society         5499
total_sqft        46
bath              57
balcony          593
price              0
bhk                0
sqrft/bhk         46
dtype: int64

In [16]:
df.dropna(inplace= True, subset='location')

In [17]:
df.dropna(inplace=True, subset= 'sqrft/bhk')

In [18]:
df.isnull().sum()

area_type          0
availability       0
location           0
size               0
society         5469
total_sqft         0
bath              57
balcony          589
price              0
bhk                0
sqrft/bhk          0
dtype: int64

In [19]:
quantile1 = df['sqrft/bhk'].quantile(0.003)
quantile2 = df['sqrft/bhk'].quantile(0.997)

In [20]:
df1 = df[(df['sqrft/bhk'] > quantile1) & (df['sqrft/bhk'] < quantile2)]

In [21]:
df1.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk,sqrft/bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2.0,528.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4.0,650.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00,3.0,480.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3.0,507.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00,2.0,600.0

In [22]:
df1.describe()

,total_sqft,bath,balcony,price,bhk,sqrft/bhk
count,13175.000000,13118.000000,12602.000000,13175.000000,13175.000000,13175.000000
mean,1524.895729,2.675560,1.585542,110.035754,2.785351,563.563353
std,838.300385,1.272063,0.815408,134.659013,1.211032,187.478179
min,250.000000,1.000000,0.000000,8.000000,1.000000,100.000000
25%,1100.000000,2.000000,1.000000,50.000000,2.000000,475.000000
50%,1275.000000,2.000000,2.000000,71.050000,3.000000,552.000000
75%,1671.000000,3.000000,2.000000,120.000000,3.000000,625.000000
max,12000.000000,27.000000,3.000000,3600.000000,27.000000,1906.666667

In [23]:
quantile11 = df1['total_sqft'].quantile(0.997)
quantile22 = df1['total_sqft'].quantile(0.003)

In [24]:
df2 = df1[(df1['total_sqft']<quantile11)&(df1['total_sqft']>quantile22)]

In [25]:
quantile111 = df1['bath'].quantile(0.997)
quantile222 = df1['bath'].quantile(0.003)

In [26]:
df3 = df2[(df2['bath'] >= quantile222) & (df2['bath'] <= quantile111)]

In [27]:
df3['bath'].describe()

count    13012.000000
mean         2.650092
std          1.170365
min          1.000000
25%          2.000000
50%          2.000000
75%          3.000000
max          9.000000
Name: bath, dtype: float64

In [28]:
df3.describe()

,total_sqft,bath,balcony,price,bhk,sqrft/bhk
count,13012.000000,13012.000000,12528.000000,13012.000000,13012.000000,13012.000000
mean,1503.429814,2.650092,1.587165,106.604193,2.764525,561.331808
std,746.693202,1.170365,0.813729,113.337740,1.132200,178.277445
min,412.500000,1.000000,0.000000,9.000000,1.000000,100.000000
25%,1100.000000,2.000000,1.000000,50.000000,2.000000,475.000000
50%,1274.500000,2.000000,2.000000,71.000000,3.000000,552.500000
75%,1660.000000,3.000000,2.000000,120.000000,3.000000,625.000000
max,6150.000000,9.000000,3.000000,2600.000000,12.000000,1906.666667

In [29]:
df3.loc[:, 'price/sqrft'] = df3['price']/df3['total_sqft']

/tmp/ipython-input-790513338.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.loc[:, 'price/sqrft'] = df3['price']/df3['total_sqft']

In [31]:
df3.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk,sqrft/bhk,price/sqrft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2.0,528.0,0.036998
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4.0,650.0,0.046154
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00,3.0,480.0,0.043056
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3.0,507.0,0.062459
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00,2.0,600.0,0.042500

In [32]:
quantile1111 = df3['price/sqrft'].quantile(0.997)
quantile22222 = df3['price/sqrft'].quantile(0.003)

In [33]:
df4 = df3[(df3['price/sqrft'] <= quantile1111) & (df3['price/sqrft'] >= quantile22222)]

In [34]:
df4.describe()

,total_sqft,bath,balcony,price,bhk,sqrft/bhk,price/sqrft
count,12936.000000,12936.000000,12463.000000,12936.000000,12936.000000,12936.000000,12936.000000
mean,1501.504386,2.648268,1.588382,104.696693,2.761673,560.950035,0.065306
std,743.016665,1.164732,0.813168,102.568273,1.125391,177.251751,0.037243
min,412.500000,1.000000,0.000000,11.000000,1.000000,100.000000,0.022727
25%,1100.000000,2.000000,1.000000,50.000000,2.000000,475.000000,0.042726
50%,1274.000000,2.000000,2.000000,71.000000,3.000000,552.500000,0.054167
75%,1656.000000,3.000000,2.000000,119.000000,3.000000,625.000000,0.072278
max,6150.000000,9.000000,3.000000,1500.000000,12.000000,1906.666667,0.291667

In [35]:
df4.isnull().sum()

area_type          0
availability       0
location           0
size               0
society         5271
total_sqft         0
bath               0
balcony          473
price              0
bhk                0
sqrft/bhk          0
price/sqrft        0
dtype: int64

In [36]:
dummy = pd.get_dummies(df4['area_type'])

In [37]:
df5 = pd.concat([df4, dummy], axis=1)

In [38]:
df5.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk,sqrft/bhk,price/sqrft,Built-up Area,Carpet Area,Plot Area,Super built-up Area
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2.0,528.0,0.036998,False,False,False,True
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4.0,650.0,0.046154,False,False,True,False
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00,3.0,480.0,0.043056,True,False,False,False
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3.0,507.0,0.062459,False,False,False,True
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00,2.0,600.0,0.042500,False,False,False,True

In [39]:
df5.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price', 'bhk', 'sqrft/bhk',
       'price/sqrft', 'Built-up  Area', 'Carpet  Area', 'Plot  Area',
       'Super built-up  Area'],
      dtype='object')

In [40]:
df5.drop(['area_type','Built-up  Area'], axis=1, inplace=True)

In [41]:
df5.head()

,availability,location,size,society,total_sqft,bath,balcony,price,bhk,sqrft/bhk,price/sqrft,Carpet Area,Plot Area,Super built-up Area
0,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2.0,528.0,0.036998,False,False,True
1,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4.0,650.0,0.046154,False,True,False
2,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00,3.0,480.0,0.043056,False,False,False
3,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3.0,507.0,0.062459,False,False,True
4,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00,2.0,600.0,0.042500,False,False,True

In [42]:
df5['is_ready'] = df5['availability'].apply(lambda x: True if "Ready" in str(x) else False)

In [43]:
df5.drop('society', axis=1,inplace= True)

In [44]:
df5.drop(['availability','size'], axis=1, inplace = True)

In [45]:
df5.columns

Index(['location', 'total_sqft', 'bath', 'balcony', 'price', 'bhk',
       'sqrft/bhk', 'price/sqrft', 'Carpet  Area', 'Plot  Area',
       'Super built-up  Area', 'is_ready'],
      dtype='object')

In [46]:
df5.head()

,location,total_sqft,bath,balcony,price,bhk,sqrft/bhk,price/sqrft,Carpet Area,Plot Area,Super built-up Area,is_ready
0,Electronic City Phase II,1056.0,2.0,1.0,39.07,2.0,528.0,0.036998,False,False,True,False
1,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4.0,650.0,0.046154,False,True,False,True
2,Uttarahalli,1440.0,2.0,3.0,62.00,3.0,480.0,0.043056,False,False,False,True
3,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3.0,507.0,0.062459,False,False,True,True
4,Kothanur,1200.0,2.0,1.0,51.00,2.0,600.0,0.042500,False,False,True,True

In [47]:
i = 0
for i in range(len(df5['location'].unique())):
  i = i+1
print(i)

1269

In [48]:
df5.location = df['location'].apply(lambda x: x.strip())

In [49]:
location_stats = df5['location'].groupby(df5['location']).count().sort_values(ascending=False)

In [50]:
less_than_10 = location_stats[location_stats <= 10]

In [51]:
df5['location'] = df5['location'].apply(lambda x: 'other' if x in less_than_10 else x)

In [52]:
df5.isnull().sum()

location                  0
total_sqft                0
bath                      0
balcony                 473
price                     0
bhk                       0
sqrft/bhk                 0
price/sqrft               0
Carpet  Area              0
Plot  Area                0
Super built-up  Area      0
is_ready                  0
dtype: int64

In [53]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [54]:
rfg = RandomForestRegressor()

In [55]:
dummies = pd.get_dummies(df5.location)
dummies.head(3)

,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,6th Phase JP Nagar,7th Phase JP Nagar,8th Phase JP Nagar,9th Phase JP Nagar,...,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,other
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [56]:
df5 = pd.concat([df5,dummies.drop('other',axis='columns')],axis='columns')
df5.drop('location',axis='columns',inplace=True)
df5.head()

,total_sqft,bath,balcony,price,bhk,sqrft/bhk,price/sqrft,Carpet Area,Plot Area,Super built-up Area,...,Vijayanagar,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur
0,1056.0,2.0,1.0,39.07,2.0,528.0,0.036998,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,2600.0,5.0,3.0,120.00,4.0,650.0,0.046154,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,1440.0,2.0,3.0,62.00,3.0,480.0,0.043056,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1521.0,3.0,1.0,95.00,3.0,507.0,0.062459,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,1200.0,2.0,1.0,51.00,2.0,600.0,0.042500,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [58]:
import json
a = df5.columns.tolist()
with open('columns.json', 'w') as f:
    json.dump(a, f)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

train_data = df5[df5['balcony'].notnull()]

test_data = df5[df5['balcony'].isnull()]

X = train_data.drop('balcony', axis=1)
y = train_data['balcony']

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

pred_valid = model.predict(X_valid)
from sklearn.metrics import mean_squared_error

rmse = np.sqrt(mean_squared_error(y_valid, pred_valid))
print(f"RMSE روی validation: {rmse:.2f}")

pred_test = model.predict(test_data.drop('balcony', axis=1))
df5.loc[df5['balcony'].isnull(), 'balcony'] = pred_test

RMSE روی validation: 0.72

In [ ]:
df5.isnull().sum()

total_sqft            0
bath                  0
balcony               0
price                 0
bhk                   0
                     ..
Yelachenahalli        0
Yelahanka             0
Yelahanka New Town    0
Yelenahalli           0
Yeshwanthpur          0
Length: 248, dtype: int64

In [ ]:
X = df5.drop(['price','price/sqrft'], axis = 1)

In [ ]:
X

,total_sqft,bath,balcony,bhk,sqrft/bhk,Carpet Area,Plot Area,Super built-up Area,is_ready,1st Block Jayanagar,...,Vijayanagar,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur
0,1056.0,2.0,1.00,2.0,528.00,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2600.0,5.0,3.00,4.0,650.00,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,1440.0,2.0,3.00,3.0,480.00,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,1521.0,3.0,1.00,3.0,507.00,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
4,1200.0,2.0,1.00,2.0,600.00,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,3453.0,4.0,0.00,5.0,690.60,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
13316,3600.0,5.0,1.83,4.0,900.00,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
13317,1141.0,2.0,1.00,2.0,570.50,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
13318,4689.0,4.0,1.00,4.0,1172.25,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
13319,550.0,1.0,1.00,1.0,550.00,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
y = df5['price']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit

In [ ]:
cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
cross_val_score(RandomForestRegressor(), X, y, cv=cv)

array([0.70917518, 0.68606292, 0.70081851, 0.71074121, 0.70380194])

In [ ]:
from sklearn.model_selection import GridSearchCV, ShuffleSplit
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.tree import DecisionTreeRegressor
import pandas as pd

def find_best_model_using_gridsearchcv(X, y):

    algos = {
        'linear_regression' : {
            'model': LinearRegression(),
            'params': {}   # normalize حذف شد
        },
        'lasso': {
            'model': Lasso(),
            'params': {
                'alpha': [1,2],
                'selection': ['random', 'cyclic']
            }
        },
        'decision_tree': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion' : ['squared_error','friedman_mse'],   # درست شد
                'splitter': ['best','random']
            }
        }
    }

    scores = []
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

    for algo_name, config in algos.items():
        gs = GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False)
        gs.fit(X,y)
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
        })

    return pd.DataFrame(scores, columns=['model','best_score','best_params'])

In [ ]:
find_best_model_using_gridsearchcv(X,y)

,model,best_score,best_params
0,linear_regression,0.691936,{}
1,lasso,0.624410,"{'alpha': 1, 'selection': 'random'}"
2,decision_tree,0.527770,"{'criterion': 'squared_error', 'splitter': 'ra..."

In [ ]:
params = {
        'n_estimators': [100, 200, 300],      
        'max_depth': [None, 5, 10, 20],       
        'min_samples_split': [2, 5, 10],      
        'min_samples_leaf': [1, 2, 4],        
        'max_features': ['auto', 'sqrt', 'log2']  
    }

ccv = GridSearchCV(estimator=RandomForestRegressor(),
             param_grid=params, n_jobs=-1)

In [ ]:
from sklearn.model_selection import RandomizedSearchCV, ShuffleSplit
from sklearn.ensemble import RandomForestRegressor
import numpy as np

def rf_randomsearch(X, y):

    params = {
        'n_estimators': np.arange(100, 500, 50),
        'max_depth': [None, 5, 10, 20, 30],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4],
        'max_features': ['auto', 'sqrt', 'log2']
    }

    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

    model = RandomForestRegressor(random_state=0)

    rs = RandomizedSearchCV(
        estimator=model,
        param_distributions=params,
        n_iter=30,          
        cv=cv,
        n_jobs=-1,
        verbose=1,
        random_state=0
    )

    rs.fit(X, y)

    return rs.best_score_, rs.best_params_

In [ ]:
a,b = rf_randomsearch(X, y)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
75 fits failed out of a total of 150.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
27 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
48 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan 0.60422177        nan 0.68209157
 0.56119339        nan        nan        nan 0.53791794 0.48039081
        nan 0.69082911 0.46827629 0.6136741  0.48577703        nan
        nan 0.6099378         nan 0.61787975        nan 0.62680895
        nan        nan        nan 0.48244791 0.61875862 0.72422439]
  warnings.warn(

In [ ]:
print(a,b)

0.7242243920137774 {'n_estimators': np.int64(100), 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 30}

In [ ]:
model = RandomForestRegressor(
    min_samples_split=5,
    min_samples_leaf=1,
    max_features='sqrt',
    max_depth=30,
    random_state=0
)

In [ ]:
cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
cross_val_score(model, X, y, cv=cv)

array([0.74769932, 0.71036995, 0.71885146, 0.72859591, 0.71560532])

In [ ]:
from sklearn.model_selection import ShuffleSplit, cross_val_score
from sklearn.ensemble import RandomForestRegressor
import pickle

model = RandomForestRegressor(
    min_samples_split=5,
    min_samples_leaf=1,
    max_features='sqrt',
    max_depth=30,
    random_state=0
)

model.fit(X, y)  

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
scores = cross_val_score(model, X, y, cv=cv)
print("Scores:", scores)
print("Mean:", scores.mean())


with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

Scores: [0.74769932 0.71036995 0.71885146 0.72859591 0.71560532]
Mean: 0.7242243920137774

In [ ]:
with open("model.pkl", "rb") as f:
    loaded_model = pickle.load(f)

In [ ]:
loaded_model.predict(X)

array([ 40.47732331, 194.77433162,  65.61722618, ...,  53.80255439,
       534.89907803,  27.6059652 ])